meta_product_name: "Energy Saver"
meta_title: "Invest in saving money"
meta_description: "Gérez tous vos objets connectés au même endroit"
meta_image: "bg.jpg"                       # should exist in `app/assets/images/`
