# config/sidekiq.yml
:concurrency: 5
:timeout: 60
:verbose: true
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
:schedule:
  update_consumption_job:
    every: '30s' 
    class: UpdateConsumptionsJob
